module.exports={
    GRUPOS: [
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "RPM",
      NombreActividad: "Mantenimiento Preventivo Programado",
      Mostrar: true,
    },
    {
      Grupo: "MCP",
      NombreGrupo: "Mantenimiento Correctivo",
      Actividad: "MCP",
      NombreActividad: "Mantenimiento Correctivo",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "MUA",
      NombreActividad: "Muestreos de Aceite",
      Mostrar: true,
    },
    {
      Grupo: "RSP",
      NombreGrupo: "Recorridos de Seguridad Público",
      Actividad: "RSP",
      NombreActividad: "Recorridos de Seguridad Público",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "RCE",
      NombreActividad: "Recorrido de Control de Estaciones",
      Mostrar: true,
    },
    {
      Grupo: "MPL",
      NombreGrupo: "Mantenimiento Preventivo No Programado",
      Actividad: "MPL",
      NombreActividad: "Mantenimiento Preventivo No Programado",
      Mostrar: true,
    },
    {
      Grupo: "MST",
      NombreGrupo: "Servicios a Terceros",
      Actividad: "MST",
      NombreActividad: "Servicios a Terceros",
      Mostrar: true,
    },
    {
      Grupo: "MAC",
      NombreGrupo: "Actividades Complementarias",
      Actividad: "MAC",
      NombreActividad: "Actividades Complementarias",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "TER",
      NombreActividad: "Termografía",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "LIT",
      NombreActividad: "LAT Inspección Terrestre",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "LMI",
      NombreActividad: "LAT Inspección Minuciosa",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "MPT",
      NombreActividad: "Medición de Resistencia de PAT",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "MRS",
      NombreActividad: "Medición de Resistividad de Suelo",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "PCA",
      NombreActividad: "Medición de Protección Catódica",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "MPT",
      NombreActividad: "LAT Inspección Minuciosa",
      Mostrar: true,
    },
    {
      Grupo: "RPM",
      NombreGrupo: "Mantenimiento Programado",
      Actividad: "RPE",
      NombreActividad: "Recorrido Periódico",
      Mostrar: true,
    },
  ]}